# .github/workflows/douban.yml
name: douban
on:
  push:
    branches:
      - master
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: drama
      uses: lizheming/doumark-action@master
      with:
        id: 171320005
        type: drama
        format: csv
        dir: ./data/douban
        
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './data/douban'
